# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Cascade
version:      0.01
version_from: lib/Config/Cascade.pm
installdirs:  site
requires:
    Regexp::Common:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
